[package]
name = "animation-no-wasm-bindgen-start"
version = "0.1.0"
authors = ["David O'Connor <david.alan.oconnor@gmail.com>"]
edition = "2018"

[dependencies]
seed = {path = "../../"}
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
