[package]
name = "experimental_component"
version = "0.1.0"
authors = ["glennsl"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = { path = "../../", features = ["experimental-component-api"] }
